name: LeeTest
favicon: null
layout_spectrum: 0.7291082579176873
typography_spectrum: 0.7954309552442282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7208142755553126
  lightness: 0.42199421557597816
  saturation: 0.5303757272195071
  rhythmicContrast: 0.5968632546719164
purpose: []
